name: micronsbinder_02
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=openblas
  - bottleneck=1.4.2=py39ha9d4c09_0
  - ca-certificates=2025.9.9=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libopenblas=0.3.30=h46f56fc_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - numpy-base=2.0.1=py39h8a23956_1
  - openssl=1.1.1w=h7f8727e_0
  - pybind11-abi=4=hd3eb1b0_1
  - python=3.9.5=h12debd9_4
  - python-dateutil=2.9.0post0=py39h06a4308_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - readline=8.2=h5eee18b_0
  - setuptools=75.1.0=py39h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.44.0=py39h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - ace-tools==0.0
      - addict==2.4.0
      - aiohappyeyeballs==2.6.1
      - aiosignal==1.4.0
      - anyio==4.6.2.post1
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - argschema==3.0.4
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - async-timeout==5.0.1
      - attrs==24.2.0
      - babel==2.16.0
      - beautifulsoup4==4.12.3
      - bleach==6.2.0
      - blinker==1.9.0
      - blosc==1.11.2
      - blosc2==2.5.1
      - boto3==1.35.71
      - botocore==1.35.71
      - bounded-pool-executor==0.0.3
      - brotli==1.1.0
      - cachetools==5.5.0
      - caveclient==8.0.0
      - certifi==2024.8.30
      - cffi==1.17.1
      - chardet==5.2.0
      - charset-normalizer==3.4.0
      - click==8.1.7
      - cloud-files==4.29.0
      - cloud-volume==11.0.2
      - cloudpickle==3.1.1
      - colorcet==3.1.0
      - colorlog==6.9.0
      - comm==0.2.2
      - compressed-segmentation==2.3.1
      - configargparse==1.7.1
      - contourpy==1.3.0
      - crc32c==2.7.1
      - cryptography==45.0.5
      - cupy-cuda12x==13.4.1
      - cycler==0.12.1
      - dash==3.2.0
      - dask==2024.8.0
      - dataclasses==0.6
      - debugpy==1.8.9
      - decorator==5.1.1
      - deflate==0.7.0
      - defusedxml==0.7.1
      - dill==0.3.9
      - distro==1.9.0
      - dracopy==1.4.1
      - exceptiongroup==1.2.2
      - executing==2.1.0
      - fasteners==0.19
      - fastjsonschema==2.21.0
      - fastremap==1.15.0
      - fastrlock==0.8.3
      - filelock==3.18.0
      - flake8==7.3.0
      - flask==3.1.2
      - fonttools==4.55.0
      - fqdn==1.5.1
      - frozenlist==1.8.0
      - fsspec==2025.3.0
      - future==1.0.0
      - gevent==24.11.1
      - globus-sdk==3.60.0
      - glymur==0.14.0.post1
      - google-api-core==2.23.0
      - google-auth==2.36.0
      - google-cloud-core==2.4.1
      - google-cloud-storage==2.18.2
      - google-crc32c==1.6.0
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.66.0
      - graphviz==0.21
      - greenlet==3.1.1
      - h11==0.14.0
      - h5py==3.12.1
      - httpcore==1.0.7
      - httpx==0.28.0
      - ibl-neuropixel==1.4.0
      - iblatlas==0.5.4
      - ibllib==2.39.1
      - iblutil==1.16.0
      - idna==3.10
      - imagecodecs==2024.12.30
      - imageio==2.36.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - inflection==0.5.1
      - iniconfig==2.0.0
      - ipykernel==6.29.5
      - ipython==8.18.1
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.4
      - jmespath==1.0.1
      - joblib==1.4.2
      - json5==0.10.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.6
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - kaleido==0.2.1
      - kiwisolver==1.4.7
      - lab==8.3
      - lazy-loader==0.4
      - llvmlite==0.43.0
      - locket==1.0.0
      - lxml==6.0.2
      - markdown==3.7
      - markupsafe==3.0.2
      - marshmallow==3.26.1
      - matplotlib==3.9.4
      - matplotlib-inline==0.1.7
      - mccabe==0.7.0
      - meshparty==1.18.0
      - microviewer==1.9.0
      - mistune==3.0.2
      - mpmath==1.3.0
      - msgpack==1.1.0
      - mtscomp==1.0.2
      - multidict==6.7.0
      - multiprocess==0.70.17
      - multiwrapper==0.1.1
      - narwhals==1.26.0
      - nbclient==0.10.1
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - ndindex==1.9.2
      - nest-asyncio==1.6.0
      - networkx==2.8.8
      - notebook==7.2.2
      - notebook-shim==0.2.4
      - nptdms==1.10.0
      - numba==0.60.0
      - numexpr==2.10.2
      - numpy==1.23.5
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - oldest-supported-numpy==0.5
      - one-api==2.11.2
      - open3d==0.19.0
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.12.0.88
      - orjson==3.10.12
      - overrides==7.7.0
      - packaging==24.2
      - pandas==1.5.3
      - pandocfilters==1.5.1
      - parso==0.8.4
      - partd==1.4.2
      - pathos==0.3.3
      - patsy==1.0.1
      - pcg-skel==1.2.0
      - pexpect==4.9.0
      - phylib==2.6.1
      - pillow==11.0.0
      - pip==25.1.1
      - platformdirs==4.3.6
      - plotly==6.0.0
      - pluggy==1.5.0
      - plyfile==1.1
      - pooch==1.8.2
      - posix-ipc==1.1.1
      - pox==0.3.5
      - ppft==1.7.6.9
      - pqdm==0.2.0
      - prometheus-client==0.21.0
      - prompt-toolkit==3.0.48
      - propcache==0.4.1
      - proto-plus==1.25.0
      - protobuf==5.29.0
      - psutil==6.1.0
      - psychofit==1.0.0.post0
      - psycopg2-binary==2.9.11
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyarrow==18.1.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pycodestyle==2.14.0
      - pycparser==2.22
      - pyflakes==3.4.0
      - pygments==2.18.0
      - pyjwt==2.10.1
      - pymeshfix==0.17.0
      - pynrrd==1.1.3
      - pyparsing==3.2.0
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.17
      - pyqt5-sip==12.17.0
      - pyquaternion==0.9.9
      - pysimdjson==6.0.2
      - pytest==8.3.3
      - python-json-logger==2.0.7
      - python-jsonschema-objects==0.5.7
      - pytz==2024.2
      - pyvista==0.44.2
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - referencing==0.35.1
      - requests==2.32.3
      - requests-toolbelt==1.0.0
      - retrying==1.4.2
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.21.0
      - rsa==4.9
      - rtree==1.3.0
      - ruamel-yaml==0.18.15
      - ruamel-yaml-clib==0.2.14
      - s3transfer==0.10.4
      - scikit-build==0.18.1
      - scikit-image==0.24.0
      - scikit-learn==1.5.2
      - scipy==1.10.1
      - scooby==0.10.0
      - seaborn==0.13.2
      - semver==3.0.4
      - send2trash==1.8.3
      - shapely==2.0.6
      - simpleitk==2.5.2
      - simplejpeg==1.7.6
      - simplejson==3.19.3
      - six==1.16.0
      - skeleton-plot==0.0.10
      - slidingrp==1.1.1
      - sniffio==1.3.1
      - soupsieve==2.6
      - sparse==0.15.5
      - sqlalchemy==2.0.44
      - sqlitedict==2.1.0
      - stack-data==0.6.3
      - standard-transform==1.4.0
      - statannotations==0.7.2
      - statsmodels==0.14.4
      - sympy==1.13.1
      - tables==3.9.2
      - tenacity==9.0.0
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tifffile==2024.8.30
      - tinycss2==1.4.0
      - tomli==2.2.1
      - toolz==1.0.0
      - torch==2.6.0
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - trimesh==4.5.3
      - triton==3.2.0
      - txt2tags==3.9
      - types-python-dateutil==2.9.0.20241003
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - uri-template==1.3.0
      - urllib3==1.26.20
      - vtk==9.3.1
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.13
      - xarray==2023.1.0
      - yarl==1.22.0
      - zipp==3.21.0
      - zope-event==5.0
      - zope-interface==7.2
      - zstandard==0.23.0
prefix: /home/ckang/anaconda3/envs/micronsbinder_02
